### ISSUE TITLE
zpan-front 采用协议？

### ISSUE THREAD

**Issue by yiyungent** [saltbo/zpan-front#15]
请问一下，`zpan-front` 采用何种开源协议？
`zpan` 采用 `GPL-3.0`，`zpan-front` 也采用  `GPL-3.0` 吗？
准备基于 `zpan-front` 写个项目，谢谢

**Comment by saltbo** [comment]
是的 GPLv3



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yiyun ***@***.***&gt;
发送时间: 2021年6月18日 19:21
收件人: saltbo/zpan-front ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[saltbo/zpan-front] zpan-front 采用协议？ (#15)





 
请问一下，zpan-front 采用何种开源协议？
 zpan 采用 'GPL-3.0'，zpan-front 也采用  'GPL-3.0' 吗？
 准备基于 zpan-front 写个项目，谢谢

**Comment by yiyungent** [comment]
感谢回复！
