### ISSUE TITLE
文件批量上传的问题，这个功能比较重要，麻烦作者看一下

### ISSUE THREAD

**Issue by lzcxfz** [saltbo/zpan-front#16]
文件上传的时候，选择多个文件上传，但是，在上传过程中，如果有某个文件上传成功，文件名后面就会有一个勾，然后页面就会刷新，其他文件的上传就被中断了，希望作者解决一下。另外，如果分享文件的时候支持预览，就更好了。总体来说，做的蛮好的，感谢作者！

**Comment by saltbo** [comment]
fixed by the commit https://github.com/saltbo/zpan-front/commit/bdcc5d1407e4b9e9fd533f6b73fafc5ffc9e6cf0
