### ISSUE TITLE
单独启动前端这个项目起不来的嘛~

### ISSUE THREAD

**Issue by chen870370470** [saltbo/zpan-front#31]
单独启动前端项目报错

**Comment by saltbo** [comment]
可以啊 只是请求接口依赖后端

**Comment by chen870370470** [comment]
![image](https://user-images.githubusercontent.com/59992255/134864969-c573e9e6-6142-4b67-b74f-a8c26dbcbeb6.png)
安装完依赖，跑起来报这个错 页面出不来，请问下怎么解决呀~

**Comment by saltbo** [comment]
没遇到过，启动日志有报错么

**Comment by saltbo** [comment]
先关掉了，有问题再反馈
