### ISSUE TITLE
请问当前前端代码是否为最新版本

### ISSUE THREAD

**Issue by Yuch3nE** [saltbo/zpan-front#36]
matter.js中调用create创建文件夹时，会有报错，但是zpan二进制中打包好的前端代码能够正确执行
问题出在matter.js中create函数调用上，在src/components/Uploader/index.vue中调用是this.$zpan.File.create(this.sid, this.dist, newFile)
但是在src/views/home/disk/index.vue的openCreateFolderDiglog函数中调用变成了this.$zpan.File.create(body)
相对应的ceate函数的定义中有三个变量create(sid, dir, file)

**Comment by saltbo** [comment]
抱歉 前端代码库没有及时打tag，现在已经不知道哪次commit是最新版本了。可以按照最新版本的时间找一下，然后我可以给重新打个tag。

**Comment by saltbo** [comment]
按时间定位了个commit打了个tag

https://github.com/saltbo/zpan-front/releases/tag/v1.6.4
