### ISSUE TITLE
不支持 docx 、doc 文件格式的预览

### ISSUE THREAD

**Issue by zongwu233** [saltbo/zpan-front#41]
试用了一下，目前不支持 docx 、doc 文件格式的预览，后续是否有计划支持这些格式的文件预览？
还是采用集成 onlyoffice 的方式来做预览？

**Comment by saltbo** [comment]
<img width="1743" alt="image" src="https://github.com/saltbo/zpan-front/assets/17308208/2cdda271-f656-4cf8-a870-1aaff6d24ec9">

我试了一下，没问题啊。你可以打开开发者工具 看下这个接口里的这个type是什么。或者看下数据库
